replicas: 1

image:
  repository: gcr.io/google_containers/heapster
  tag: v1.2.0
  pullPolicy: IfNotPresent

service:
  name: heapster

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nanny:
  image:
    repository: gcr.io/google_containers/addon-resizer
    tag: "1.0"
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 50m
      memory: 32Mi
    requests:
      cpu: 50m
      memory: 32Mi
