kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: fluentd
    name: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  template:
    metadata:
      name: fluentd
      labels:
        app: fluentd
        name: {{ template "fullname" . }}
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
        - name: fluentd
          image: {{ .Values.image.repository }}:{{  .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOST
{{- if .Values.elasticsearch.host }}
              value: {{ .Values.elasticsearch.host }}
{{- else }}
              value: {{ template "fullname" . }}-es
{{- end }}
            - name: ELASTICSEARCH_PORT
              value: "{{ .Values.elasticsearch.port }}"
          volumeMounts:
            - name: config
              mountPath: /etc/td-agent/
            - name: varlog
              mountPath: /var/log
            - name: docker
              mountPath: /var/lib/docker/containers
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "fullname" . }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: docker
          hostPath:
            path: /var/lib/docker/containers
