kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: fluentd
    name: {{ template "release" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "24231"
spec:
  selector:
    app: fluentd
    name: {{ template "release" . }}
  ports:
    - name: metrics
      port: 24231
      protocol: TCP
