kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: heapster
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
spec:
  selector:
    app: heapster
    name: {{ template "release" . }}
  ports:
    - port: 80
      targetPort: 8082
