kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "release" . }}
  namespace: {{ template "namespace" . }}
data:
  grafana.ini: |
    [dashboards.json]
    enabled = true
    path = /etc/grafana-dashboards/
