{{- if not .Values.storage.disabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "release" . }}
  namespace: {{ template "namespace" . }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.storage.class }}
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
