kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: grafana
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app: grafana
    name: {{ template "fullname" . }}
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80
