replicaCount: 1
image:
  repository: kibana
  tag: 4.6
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

elasticsearch:
  protocol: http
  host: ""
  port: 9200

ingress:
  domain: ""
  annotations: ""
