kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: elasticsearch
    role: client
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9108"
spec:
  selector:
    app: elasticsearch
    role: client
    name: {{ template "release" . }}
  ports:
    - name: http
      port: 9200
      protocol: TCP
