kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "release" . }}
  namespace: {{ template "namespace" . }}
data:
  elasticsearch.yml: |
    cluster:
      name: ${CLUSTER_NAME}

    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}

    network.host: ${NETWORK_HOST}
    network.bind_host: 0.0.0.0

    path:
      data: /data/data
      logs: /data/log
      plugins: /elasticsearch/plugins
      work: /data/work

    bootstrap:
      memory_lock: true
      ignore_system_bootstrap_checks: true

    http:
      enabled: ${HTTP_ENABLE}
      compression: true
      cors:
        enabled: ${HTTP_CORS_ENABLE}
        allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

    cloud:
      kubernetes:
        service: ${DISCOVERY_SERVICE}
        namespace: ${NAMESPACE}
    discovery:
      type: kubernetes
      zen:
        minimum_master_nodes: ${NUMBER_OF_MASTERS}

    plugin.mandatory: cloud-kubernetes

  logging.yml: |
    es.logger.level: INFO
    rootLogger: ${es.logger.level}, console
    logger:
      action: DEBUG
      com.amazonaws: WARN

    appender:
      console:
        type: console
        layout:
          type: consolePattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
