kind: PetSet
apiVersion: apps/v1alpha1
metadata:
  name: {{ template "fullname" . }}-data
  labels:
    app: elasticsearch
    role: data
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  serviceName: {{ template "fullname" . }}-data
  replicas: {{ .Values.data.replicas }}
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
        name: {{ template "fullname" . }}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: [ IPC_LOCK ]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_NAME
              value: {{ .Values.cluster.name }}
            - name: DISCOVERY_SERVICE
              value: {{ template "fullname" . }}-discovery
            - name: NODE_MASTER
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
          ports:
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: storage
          resources:
{{ toYaml .Values.data.resources | indent 12 }}
        - name: metrics
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          ports:
            - containerPort: 9108
              name: metrics
              protocol: TCP
          resources:
{{ toYaml .Values.data.metrics.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: storage
        annotations:
          volume.alpha.kubernetes.io/storage-class: {{ .Values.data.storage.class }}
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: {{ .Values.data.storage.size }}
