kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" .  }}-discovery
  labels:
    app: elasticsearch
    role: master
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9108"
spec:
  selector:
    app: elasticsearch
    role: master
    name: {{ template "fullname" . }}
  ports:
    - name: transport
      port: 9300
      protocol: TCP
