{{- if .Values.ingress.domain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "release" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: elasticsearch
    role: client
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: elasticsearch.{{ .Values.ingress.domain }}
{{- end }}
  rules:
    - host: elasticsearch.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: 9200
{{- end }}
