kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: elasticsearch
    role: master
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
        name: {{ template "fullname" . }}
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
        - name: elasticsearch
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: [ IPC_LOCK ]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_NAME
              value: {{ .Values.cluster.name }}
            - name: DISCOVERY_SERVICE
              value: {{ .Values.service.name }}-discovery
            - name: NODE_MASTER
              value: "true"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
          ports:
            - name: transport
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: config
              mountPath: /elasticsearch/config/
          resources:
{{ toYaml .Values.master.resources | indent 12 }}
        - name: metrics
          image: {{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9108
              protocol: TCP
          resources:
{{ toYaml .Values.master.metrics.resources | indent 12 }}
      volumes:
        - name: storage
          emptyDir: {}
        - name: config
          configMap:
            name: {{ template "fullname" . }}
