{{- if .Values.rbac }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ template "release" . }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
    nonResourceURLs: []

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ template "release" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "release" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "release" . }}
  namespace: {{ .Release.Namespace }}
  apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- end }}
