kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "release" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: kibana
    name: {{ template "release" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: kibana
        name: {{ template "release" . }}
    spec:
      containers:
        - name: kibana
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{- if .Values.elasticsearch.host }}
            - --elasticsearch={{ .Values.elasticsearch.protocol }}://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}
{{- else }}
            - --elasticsearch={{ .Values.elasticsearch.protocol }}://{{ template "release" . }}-es:{{ .Values.elasticsearch.port }}
{{- end }}
          ports:
            - containerPort: 5601
              name: ui
          resources:
{{ toYaml .Values.resources | indent 12 }}
