kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: kibana
    name: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
    - name: ui
      port: 80
      targetPort: ui
  selector:
    app: kibana
    name: {{ template "fullname" . }}
