kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: kibana
    name: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app: kibana
    name: {{ template "fullname" . }}
  ports:
    - name: ui
      port: 80
      targetPort: ui
