kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: blackbox-exporter
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app: blackbox-exporter
    name: {{ template "release" . }}
  ports:
    - protocol: TCP
      targetPort: 9115
      port: 80
