ingress-nginx:
  nameOverride: nginx-public
  class: private
  service:
    name: ingress-nginx
  default_backend:
    service:
      name: default-backend

ingress-dns-manager:
  ingress:
    service: ingress-nginx
