global:
  name: ""

image:
  repository: quay.io/prometheus/alertmanager
  tag: v0.5.0
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

storage:
  disabled: false
  class: default
  size: 10Gi

service:
  name: alertmanager

ingress:
  tls: false
  domain: ""
  annotations: ""

reloader:
  image:
    repository: jimmidyson/configmap-reload
    tag: v0.1
    pullPolicy: IfNotPresent

config: |
  global:
    # slack_api_url: '...' # example slack configuration

  route:
    receiver: default-receiver
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 3h

  receivers:
    - name: default-receiver
      slack_configs:
        - channel: "#alerts"
          send_resolved: true
