kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "release" . }}-default
  namespace: {{ template "namespace" . }}
  labels:
    app: nginx-default-backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-default-backend
        name: {{ template "release" . }}
    spec:
      containers:
        - name: default-backend
          image: {{ .Values.default_backend.image.repository }}:{{ .Values.default_backend.image.tag }}
          imagePullPolicy: {{ .Values.default_backend.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.default_backend.resources | indent 12 }}
