kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ template "namespace" . }}
  labels:
    app: nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
    name: {{ template "release" . }}
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
