kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "release" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: nginx
        name: {{ template "release" . }}
    spec:
      serviceAccount: {{ template "release" . }}
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 443
          args:
            - /nginx-ingress-controller
            - --logtostderr
{{- if .Values.class }}
            - --ingress-class={{ .Values.class }}
{{- end}}
            - --default-backend-service=$(POD_NAMESPACE)/{{ .Values.default_backend.service.name }}
            - --nginx-configmap=$(POD_NAMESPACE)/{{ template "release" . }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
