{{- if .Values.rbac }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ template "fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["endpoints", "secrets", "configmaps", "pods", "nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events", "services"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ template "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- end }}
