rbac: true

global:
  name: ""
  namespace: ""

image:
  repository: quay.io/roboll/fluentd-kubernetes
  tag: v1.19
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

elasticsearch:
  host: ""
  port: 9200

service:
  name: fluentd
