kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  labels:
    app: blackbox-exporter
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
        name: {{ template "fullname" . }}
    spec:
      containers:
        - name: blackbox-exporter
          image: {{ .Values.blackbox.image.repository }}:{{ .Values.blackbox.image.tag }}
          imagePullPolicy: {{ .Values.blackbox.image.pullPolicy }}
          ports:
            - containerPort: 9115
              protocol: TCP
          resources:
{{ toYaml .Values.blackbox.resources | indent 12 }}
