kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "release" . }}
  namespace: {{ template "namespace" . }}
data:
  prometheus.yml: >
{{ .Files.Get "prometheus.yml" | indent 4 }}
{{ .Values.config.extra | indent 4 }}
  rules: >
{{ .Values.config.rules | indent 4 }}
  alerts: >
{{ .Values.config.alerts | indent 4 }}
