kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
data:
  prometheus.yml: >
{{ .Files.Get "prometheus.yml" | indent 4 }}
  rules: >
{{ .Files.Get "rules" | indent 4 }}
  alerts: >
{{ .Files.Get "alerts" | indent 4 }}
