kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-node-exporter
  labels:
    app: node-exporter
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  template:
    metadata:
      labels:
        app: node-exporter
        name: {{ template "fullname" . }}
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: node-exporter
          image: {{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}
          imagePullPolicy: {{ .Values.node.image.pullPolicy }}
          ports:
            - name: scrape
              containerPort: 9100
          resources:
{{ toYaml .Values.node.resources | indent 12 }}
