kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: prometheus
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: prometheus
    name: {{ template "fullname" . }}
  ports:
    - protocol: TCP
      targetPort: 9090
      port: 80
