rbac: true

replicas: 1

image:
  repository: quay.io/roboll/nginx-ingress-controller
  tag: 0.8.4
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  name: ingress
  type: LoadBalancer

default_backend:
  image:
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    name: ingress-default-backend
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi

class: ""
config:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  body-size: "64m"
