kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: alertmanager
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: alertmanager
        name: {{ template "fullname" . }}
    spec:
      containers:
        - name: configmap-reload
          image: {{ .Values.reloader.image.repository }}:{{ .Values.reloader.image.tag }}
          imagePullPolicy: {{ .Values.reloader.image.pullPolicy }}
          args:
            - --volume-dir=/etc/alertmanager
            - --webhook-url=http://localhost:9093/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
              readOnly: true
        - name: alertmanager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -config.file=/etc/alertmanager/alertmanager.yml
            - -storage.path=/data
{{- if .Values.ingress.domain }}
{{- if .Values.ingress.tls }}
            - -web.external-url=https://alerts.{{ .Values.ingress.domain }}
{{- else }}
            - -web.external-url=http://alerts.{{ .Values.ingress.domain }}
{{- end }}
{{- end }}
          ports:
            - containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: config
              mountPath: /etc/alertmanager
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "fullname" . }}
        - name: storage
{{- if .Values.storage.disabled }}
          emptyDir: {}
{{- else }}
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}
{{- end }}
