kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ template "namespace" . }}
  labels:
    app: alertmanager
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: alertmanager
    name: {{ template "release" . }}
  ports:
    - protocol: TCP
      targetPort: 9093
      port: 80
