nameOverride: node-exporter
rbac: true

global:
  name: ""

image:
  repository: quay.io/prometheus/node-exporter
  tag: 0.12.0
  pullPolicy: IfNotPresent

service:
  name: node-exporter

resources:
  limits:
    cpu: 50m
    memory: 16Mi
  requests:
    cpu: 50m
    memory: 16Mi
