global:
  name: ""

image:
  repository: grafana/grafana
  tag: 3.1.0
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

storage:
  disabled: false
  class: default
  size: 10Gi

service:
  name: grafana

ingress:
  tls: false
  domain: ""
  annotations: ""
