{{- if .Values.rbac }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ template "release" . }}
rules:
  - apiGroups: [""]
    resources: ["events", "secrets"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["stable.k8s.psg.io"]
    resources: ["certificates"]
    verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ template "release" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "release" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "release" . }}
  namespace: {{ .Release.Namespace }}
  apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- end }}
