{{- if .Values.secret.vault.path }}
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- $fullname := printf "%s-%s" .Release.Name $name | trunc 24 -}}
{{- $secret := or (.Values.secret.name) ($fullname)}}
  name: {{ $secret }}
spec:
  type: Opaque
  path: {{ .Values.secret.vault.path }}
{{- end }}
